//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bdots1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentID { get; set; }
        public int videoID { get; set; }
        public int payer { get; set; }
        public int receiver { get; set; }
        public System.DateTime paymentDatetime { get; set; }
        public decimal paymentSum { get; set; }
    
        public virtual CertUser Payers { get; set; }
        public virtual CertUser Receivers { get; set; }
        public virtual Video Videos { get; set; }
    }
}
